"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
import os
import environ
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", "secretkeytesting")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", True)

ALLOWED_HOSTS = ["app.expgrowthdigital.com", "localhost", "127.0.0.1", ]

INTERNAL_APPS = ["amazon", "authentication"]
EXTERNAL_APPS = ["rest_framework",]
DEFAULT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


# Application definition

INSTALLED_APPS = DEFAULT_APPS + INTERNAL_APPS + EXTERNAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("DATABASE_NAME", "db"),  # noqa
#         "USER": os.getenv("DATABASE_USER", "user"),  # noqa
#         "PASSWORD": os.getenv("DATABASE_PASSWORD", "password"),  # noqa
#         "HOST": os.getenv("DATABASE_HOST", "localhost"),  # noqa
#         "PORT": os.getenv("DATABASE_PORT", "5432"),  # noqa
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "mydatabase",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AMAZON_CONFIG = {
    "AMAZON_CLIENT_ID": env.str("AMAZON_CLIENT_ID", ""),
    "AMAZON_CLIENT_SECRET": env.str("AMAZON_CLIENT_SECRET", ""),
    "AMAZON_APP_ID": env.str("AMAZON_APP_ID", ""),
    "AMAZON_TOKEN_BASE_URL": env.str("AMAZON_TOKEN_BASE_URL", ""),
}


GOOGLE_OAUTH_CONFIG = {
    "GOOGLE_OAUTH_CLIENT_ID": env.str("GOOGLE_OAUTH_CLIENT_ID", ""),
    "GOOGLE_OAUTH_CLIENT_SECRET": env.str("GOOGLE_OAUTH_CLIENT_SECRET", ""),
    "GOOGLE_OAUTH_CALLBACK_URL": env.str("GOOGLE_OAUTH_CALLBACK_URL", ""),
    "GOOGLE_ID_TOKEN_INFO_URL": env.str("GOOGLE_ID_TOKEN_INFO_URL", ""),
    "GOOGLE_ACCESS_TOKEN_OBTAIN_URL": env.str("GOOGLE_ACCESS_TOKEN_OBTAIN_URL", ""),
    "GOOGLE_USER_INFO_URL": env.str("GOOGLE_USER_INFO_URL", ""),
    "GOOGLE_AUTHORIZATION_URL": env.str("GOOGLE_AUTHORIZATION_URL", ""),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}


# URL to access static files
STATIC_URL = '/static/'

# Optional: Directories where Django will search for static files

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

## Environments ###
ENVIRONMENT = os.getenv("ENVIRONMENT", "DEVELOPMENT")
AWS_ENV = os.getenv("AWS_ENV", "SANDBOX")


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            "formatter": "verbose"
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "../logs/django_all_logs.log"),
            "formatter": "simple",
        },
    },
    "loggers": {
        "": {
            "handlers": ["file"],
            "level": "INFO",
        },
    },
    "formatters": {
        "simple": {
            "format": "%(levelname)s %(message)s"
        },
        "verbose": {
            "format": "%(asctime)s | %(levelname)s | %(module)s  | %(funcName)d | %(message)s"
        }
    }
}
