# Generated by Django 5.1.4 on 2025-02-21 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAdsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=500)),
                ('marketplace_id', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=255)),
                ('amazon_seller_id', models.CharField(max_length=255)),
                ('profile_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'amazon_seller_id', 'marketplace_id')},
            },
        ),
    ]
