# Generated by Django 5.1.4 on 2025-03-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAdsSaleAsin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255)),
                ('sales_date', models.DateField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
            ],
            options={
                'unique_together': {('amazon_ads', 'asin', 'sales_date')},
            },
        ),
        migrations.CreateModel(
            name='AmazonAdsSaleCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_id', models.CharField(max_length=255)),
                ('sales_date', models.DateField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_sold', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign_bidding_strategy', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amazon_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon_ads.amazonadsaccount')),
            ],
            options={
                'unique_together': {('amazon_ads', 'campaign_id', 'sales_date')},
            },
        ),
    ]
