# Generated by Django 5.1.4 on 2025-03-25 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_delete_marketplace_remove_regiondetail_created_at_and_more'),
        ('amazon_ads', '0002_amazonadssaleasin_amazonadssalecampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonadssalecampaign',
            name='amazon_ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.seller'),
        ),
        migrations.AlterField(
            model_name='amazonadssaleasin',
            name='amazon_ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.seller'),
        ),
        migrations.DeleteModel(
            name='AmazonAdsAccount',
        ),
    ]
