# Generated by Django 5.1.4 on 2025-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0003_alter_amazonadssalecampaign_amazon_ads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadssaleasin',
            name='orders',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
