# Generated by Django 5.1.4 on 2025-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0004_amazonadssaleasin_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadssalecampaign',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
