# Generated by Django 5.1.4 on 2025-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0005_amazonadssalecampaign_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadssalecampaign',
            name='campaign_type',
            field=models.CharField(choices=[], max_length=256, null=True),
        ),
    ]
