# Generated by Django 5.1.4 on 2025-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_alter_seller_ads_refresh_token_and_more'),
        ('amazon_ads', '0006_amazonadssalecampaign_campaign_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazonadssaleasin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='amazonadssaleasin',
            name='campaign_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='amazonadssaleasin',
            unique_together={('amazon_ads', 'asin', 'sales_date', 'campaign_type')},
        ),
        migrations.AlterUniqueTogether(
            name='amazonadssalecampaign',
            unique_together={('amazon_ads', 'campaign_id', 'sales_date', 'campaign_type')},
        ),
    ]
