# Generated by Django 5.1.4 on 2025-04-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_alter_seller_ads_refresh_token_and_more'),
        ('amazon_ads', '0007_alter_amazonadssaleasin_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazonadssalecampaign',
            unique_together={('amazon_ads', 'campaign_name', 'sales_date', 'campaign_type')},
        ),
        migrations.RemoveField(
            model_name='amazonadssalecampaign',
            name='campaign_id',
        ),
    ]
