# Generated by Django 5.1.4 on 2025-04-18 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0008_alter_amazonadssalecampaign_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonadssalecampaign',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='amazonadssalecampaign',
            name='units_sold',
        ),
    ]
