# Generated by Django 5.1.4 on 2025-05-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0012_alter_sellercentraltraffic_unique_together'),
        ('amazon_ads', '0009_remove_amazonadssalecampaign_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadssaleasin',
            name='campaign_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='amazonadssaleasin',
            name='campaign_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=256)),
                ('sales', models.FloatField()),
                ('units_sold', models.IntegerField()),
                ('cost', models.FloatField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('targeting', models.CharField(max_length=256)),
                ('campaign_name', models.CharField(max_length=256)),
                ('campaign_id', models.CharField(max_length=256)),
                ('keyword', models.CharField(max_length=256)),
                ('keyword_id', models.CharField(max_length=256)),
                ('keyword_type', models.CharField(max_length=256)),
                ('keyword_bid', models.CharField(max_length=256)),
                ('ad_group_name', models.CharField(max_length=256)),
                ('ad_group_id', models.CharField(max_length=256)),
                ('search_term_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.seller')),
            ],
            options={
                'unique_together': {('seller', 'search_term', 'campaign_id', 'search_term_date')},
            },
        ),
    ]
