# Generated by Django 5.1.4 on 2025-05-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0010_amazonadssaleasin_campaign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='match_type',
            field=models.CharField(default='s', max_length=256),
            preserve_default=False,
        ),
    ]
