# Generated by Django 5.1.4 on 2025-05-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0011_searchterm_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='orders',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
