# Generated by Django 5.1.4 on 2025-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0013_alter_amazonadssaleasin_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadssalecampaign',
            name='campaign_id',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
