# Generated by Django 5.1.4 on 2025-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0014_amazonadssalecampaign_campaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonadssaleasin',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amazonadssaleasin',
            name='cpc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amazonadssaleasin',
            name='sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amazonadssaleasin',
            name='spend',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amazonadssalecampaign',
            name='cpc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amazonadssalecampaign',
            name='sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amazonadssalecampaign',
            name='spend',
            field=models.FloatField(),
        ),
    ]
