# Generated by Django 5.1.4 on 2025-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0015_alter_amazonadssaleasin_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonadssaleasin',
            name='ad_group_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='amazonadssaleasin',
            name='ad_group_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
