# Generated by Django 5.1.4 on 2025-07-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_alter_searchquerymarketbasket_combination_pct_and_more'),
        ('amazon_ads', '0016_amazonadssaleasin_ad_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='campaign_type',
            field=models.CharField(default='SPONSORED_PRODUCTS', max_length=256),
        ),
        migrations.CreateModel(
            name='Targeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.FloatField()),
                ('units_sold', models.IntegerField()),
                ('orders', models.IntegerField()),
                ('cost', models.FloatField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('targeting', models.CharField(max_length=256)),
                ('campaign_name', models.CharField(max_length=256)),
                ('campaign_id', models.CharField(max_length=256)),
                ('keyword', models.CharField(max_length=256)),
                ('keyword_id', models.CharField(max_length=256)),
                ('keyword_type', models.CharField(max_length=256)),
                ('keyword_bid', models.CharField(max_length=256)),
                ('ad_group_name', models.CharField(max_length=256)),
                ('ad_group_id', models.CharField(max_length=256)),
                ('campaign_type', models.CharField(max_length=256)),
                ('targeting_date', models.DateField()),
                ('match_type', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.seller')),
            ],
            options={
                'unique_together': {('seller', 'targeting', 'campaign_id', 'targeting_date')},
            },
        ),
    ]
