# Generated by Django 5.1.4 on 2025-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0017_searchterm_campaign_type_targeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targeting',
            name='keyword',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='targeting',
            name='keyword_bid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='targeting',
            name='keyword_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='targeting',
            name='keyword_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
