# Generated by Django 5.1.4 on 2025-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0018_alter_targeting_keyword_alter_targeting_keyword_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targeting',
            name='match_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
