# Generated by Django 5.1.4 on 2025-07-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0019_alter_targeting_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='targeting',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
