# Generated by Django 5.1.4 on 2025-07-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ads', '0020_alter_searchterm_targeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='targeting',
            name='campaign_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='targeting',
            name='keyword_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='targeting',
            name='top_of_search_is',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
