# Generated by Django 5.1.4 on 2025-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_alter_searchquerymarketbasket_combination_pct_and_more'),
        ('amazon_ads', '0021_targeting_campaign_status_targeting_keyword_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targeting',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='targeting',
            name='campaign_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='targeting',
            unique_together={('seller', 'targeting', 'campaign_id', 'targeting_date', 'campaign_type')},
        ),
    ]
