# Generated by Django 5.1.4 on 2025-07-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_alter_searchquerymarketbasket_combination_pct_and_more'),
        ('amazon_ads', '0022_alter_targeting_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targeting',
            unique_together={('seller', 'targeting', 'keyword_id', 'campaign_id', 'targeting_date', 'campaign_type')},
        ),
    ]
