# Generated by Django 5.1.4 on 2025-08-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_alter_searchquerymarketbasket_combination_pct_and_more'),
        ('amazon_ads', '0023_alter_targeting_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazonadssaleasin',
            unique_together={('amazon_ads', 'asin', 'sales_date', 'campaign_type', 'campaign_id', 'ad_group_id')},
        ),
    ]
