# Generated by Django 5.1.4 on 2025-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0016_asinmapper'),
        ('amazon_ads', '0024_alter_amazonadssaleasin_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazonadssaleasin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='amazonadssaleasin',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='amazonadssaleasin',
            unique_together={('amazon_ads', 'asin', 'sales_date', 'campaign_type', 'campaign_id', 'ad_group_id', 'sku')},
        ),
    ]
