# Generated by Django 5.1.4 on 2025-02-05 06:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_seller_sellercentralsale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('user', 'marketplace_id')},
        ),
    ]
