# Generated by Django 5.1.4 on 2025-02-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_alter_seller_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='marketplace',
            field=models.CharField(default='IN', max_length=255),
            preserve_default=False,
        ),
    ]
