# Generated by Django 5.1.4 on 2025-02-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_seller_marketplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='access_token',
        ),
        migrations.CreateModel(
            name='SellerCentralReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255)),
                ('return_request_date', models.DateField()),
                ('return_delivery_date', models.DateField()),
                ('return_type', models.CharField(max_length=255)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCentralTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_date', models.DateField()),
                ('child_asin', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('browser_sessions', models.IntegerField()),
                ('mobile_app_sessions', models.IntegerField()),
                ('browser_page_views', models.IntegerField()),
                ('mobile_app_page_views', models.IntegerField()),
                ('unit_sessions_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.seller')),
            ],
        ),
    ]
