# Generated by Django 5.1.4 on 2025-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_regiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiondetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
