# Generated by Django 5.1.4 on 2025-03-25 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_regiondetail_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('user', 'marketplace_id', 'amazon_seller_id')},
        ),
        migrations.AddField(
            model_name='seller',
            name='ads_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='country_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='marketplace',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='refresh_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
