# Generated by Django 5.1.4 on 2025-03-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_seller_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketPlace',
        ),
        migrations.RemoveField(
            model_name='regiondetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='regiondetail',
            name='updated_at',
        ),
    ]
