# Generated by Django 5.1.4 on 2025-03-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_delete_marketplace_remove_regiondetail_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellercentralsale',
            old_name='items_ordered',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='sellercentralsale',
            old_name='ordered_product_sales',
            new_name='sales',
        ),
    ]
