# Generated by Django 5.1.4 on 2025-04-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_rename_items_ordered_sellercentralsale_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='ads_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='country_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='marketplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
