# Generated by Django 5.1.4 on 2025-04-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_alter_seller_ads_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellercentraltraffic',
            unique_together={('seller', 'sessions_date', 'child_asin')},
        ),
    ]
