# Generated by Django 5.1.4 on 2025-06-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0012_alter_sellercentraltraffic_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellercentralsale',
            unique_together={('seller', 'child_asin', 'sales_date')},
        ),
    ]
