# Generated by Django 5.1.4 on 2025-07-04 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_alter_sellercentralsale_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryMarketBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255)),
                ('purchased_with_asin', models.CharField(max_length=255)),
                ('purchased_with_rank', models.IntegerField()),
                ('report_period', models.CharField(choices=[('WEEK', 'WEEK'), ('MONTH', 'MONTH')], max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('combination_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.seller')),
            ],
            options={
                'unique_together': {('seller', 'asin', 'purchased_with_asin', 'report_period')},
            },
        ),
    ]
