# Generated by Django 5.1.4 on 2025-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0014_searchquerymarketbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquerymarketbasket',
            name='combination_pct',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sellercentralreturn',
            name='refund_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sellercentraltraffic',
            name='unit_sessions_percentage',
            field=models.FloatField(),
        ),
    ]
