# Generated by Django 5.1.4 on 2025-09-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_alter_searchquerymarketbasket_combination_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsinMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
