# Generated by Django 5.1.4 on 2025-09-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0016_asinmapper'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellercentralsale',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sellercentralsale',
            name='sku',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sellercentralsale',
            unique_together={('seller', 'child_asin', 'sales_date', 'sku')},
        ),
    ]
