# Generated by Django 5.1.4 on 2025-09-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0017_alter_sellercentralsale_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asinmapper',
            name='brand',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
