# Generated by Django 5.1.4 on 2025-09-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0018_asinmapper_brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellercentraltraffic',
            unique_together={('seller', 'sessions_date', 'child_asin', 'sku')},
        ),
    ]
